### ISSUE TITLE
_fife not found at python3.5 and FIFE version 0.4.1+build.f6dff2c

### ISSUE THREAD

**Issue by MarkusHackspacher** [fifengine/fifengine#1032]
I build the fifengine from the actual git version and got an error with 
python3 -c 'from fife import fife; print(fife.getVersion())'
ImportError: /usr/lib/python3/dist-packages/fife/_fife.so: undefined symbol: _ZN3fcn6Widget11drawOutlineEPNS_8GraphicsE.

```
$ mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
== Updating version.h with version information and git meta data.

== Building FIFE version 0.4.1+build.f6dff2c using build type 'Release'.
--     Source directory is '/home/mar/workspace/python/src/fifengine'.
--     Build  directory is '/home/mar/workspace/python/src/fifengine/_build'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/mar/workspace/python/src/fifengine/../fifengine-dependencies'.

--     CMake version is '3.7.2'.
--     CXX Compiler ID: 'GNU'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found PythonInterp: /usr/bin/python3.5 (found version "3.5.3") 
-- Found the following FifeChan libraries:
--   fifechan_sdl
-- Found the following FifeChan libraries:
--   fifechan_opengl
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable exact version "3.5.3+") 
--     Python install directory is '/usr/lib/python3/dist-packages/fife'.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mar/workspace/python/src/fifengine/_build

EDIT: Delete make and make install.
$ python3 -c 'from fife import fife; print(fife.getVersion())'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fife/fife.py", line 22, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 938, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /usr/lib/python3/dist-packages/fife/_fife.so: undefined symbol: _ZN3fcn6Widget11drawOutlineEPNS_8GraphicsE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/fife/fife.py", line 25, in <module>
    _fife = swig_import_helper()
  File "/usr/lib/python3/dist-packages/fife/fife.py", line 24, in swig_import_helper
    return importlib.import_module('_fife')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_fife'
```

**Comment by MarkusHackspacher** [comment]
Could it be:
make install in Travis:
```
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/python3/dist-packages/fife/_fife.so
-- Removed runtime path from "/usr/lib/python3/dist-packages/fife/_fife.so"
```
and at me:
```
-- Install configuration: "Release"
-- Installing: /usr/lib/python3/dist-packages/fife/_fife.so
-- Set runtime path of "/usr/lib/python3/dist-packages/fife/_fife.so" to ""
```
Make the `Removed runtime path` and `Set runtime path` the different?

**Comment by MarkusHackspacher** [comment]
The first cmake call was not complete, I make it a debian sid system.
```
$ mkdir _build1; cd _build1; cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.5 PYTHON_INCLUDE_DIR=/usr/include/python3.5m -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
== Updating version.h with version information and git meta data.
-- Set CMAKE_BUILD_TYPE to default 'Release'.

== Building FIFE version 0.4.1+build.32595b1 using build type 'Release'.
--     Source directory is '/home/mar/workspace/python/src/fifengine'.
--     Build  directory is '/home/mar/workspace/python/src/fifengine/_build1'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/mar/workspace/python/src/fifengine/../fifengine-dependencies'.

--     CMake version is '3.7.2'.
--     CXX Compiler ID: 'GNU'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found                                                                                                                             
-- Found Threads: TRUE                                                                                                                                                       
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread                                                                        
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so (found version "2.0.1")                                                                                      
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so (found version "2.0.14")                                                                                         
-- Boost version: 1.62.0                                                                                                                                                     
-- Found the following Boost libraries:                                                                                                                                      
--   system                                                                                                                                                                  
--   filesystem                                                                                                                                                              
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")                                                                                                     
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.30")                                                                                                   
-- Found OPENALSOFT: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so  
-- Found vorbisfile: /usr/lib/x86_64-linux-gnu/libvorbisfile.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so (found version "2.0.0") 
-- Found PythonInterp: /usr/bin/python3.5 (found version "3.5.3") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found version "3.5.3+") 
-- Found the following FifeChan libraries:
--   fifechan_sdl
-- Found FIFECHAN: /usr/lib/libfifechan.so   
-- Found the following FifeChan libraries:
--   fifechan_opengl
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.10") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable exact version "3.5.3+") 
--     Python install directory is '/usr/lib/python3/dist-packages/fife'.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mar/workspace/python/src/fifengine/_build1
```

**Comment by LinuxDonald** [comment]
Could you upgrade to an higher swig version? Because I think 3.0.10 had an bug.

**Comment by MarkusHackspacher** [comment]
Now I have swig 3.0.12, the newest from the homepage. but the same error:

```
$ python3 -c 'from fife import fife; print(fife.getVersion())'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/fife/fife.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 938, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: /usr/lib/python3/dist-packages/fife/_fife.so: undefined symbol: _ZN3fcn6Widget11drawOutlineEPNS_8GraphicsE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/fife/fife.py", line 21, in <module>
    _fife = swig_import_helper()
  File "/usr/lib/python3/dist-packages/fife/fife.py", line 20, in swig_import_helper
    return importlib.import_module('_fife')
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: No module named '_fife'


$ mkdir _build1; cd _build1; cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.5 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DSWIG_EXECUTABLE=/usr/local/bin/swig -DCMAKE_INSTALL_PREFIX:PATH=/usr ..        
mkdir: das Verzeichnis „_build1“ kann nicht angelegt werden: Die Datei existiert bereits
== Updating version.h with version information and git meta data.

== Building FIFE version 0.4.1+build.4cf99f2 using build type 'Release'.
--     Source directory is '/home/mar/workspace/python/src/fifengine'.
--     Build  directory is '/home/mar/workspace/python/src/fifengine/_build1'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/mar/workspace/python/src/fifengine/../fifengine-dependencies'.

--     CMake version is '3.7.2'.
--     CXX Compiler ID: 'GNU'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found version "3.5.3+") 
-- Found the following FifeChan libraries:
--   fifechan_sdl
-- Found the following FifeChan libraries:
--   fifechan_opengl
-- Found SWIG: /usr/local/bin/swig (found version "3.0.12") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable exact version "3.5.3+") 
--     Python install directory is '/usr/lib/python3/dist-packages/fife'.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mar/workspace/python/src/fifengine/_build1
```

**Comment by LinuxDonald** [comment]
Have you build fifechan with: cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
Maybe build fife with: cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.5 -DCMAKE_INSTALL_PREFIX:PATH=/usr ..

**Comment by MarkusHackspacher** [comment]
I see not in fifechan that it look for python.
https://github.com/fifengine/fifechan/blob/master/CMakeLists.txt

I tryed to build the relase fifechan 0.1.4 and fifengine 0.4.1. with python3.5, I got a shorter faultmessage if I look the version. For the exakt fault I looking this evening.

**Comment by LinuxDonald** [comment]
Don't use fifechan release version. There is something broken.

**Comment by helios2000** [comment]
If you build fife it builds the python binding for fifechan.
https://github.com/fifengine/fifengine/blob/master/CMakeLists.txt#L813

**Comment by MarkusHackspacher** [comment]
@LinuxDonald your suggestion not works!
```
fifechan$ mkdir _build; cd _build; cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.5  -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- The C compiler identification is GNU 6.4.0
-- The CXX compiler identification is GNU 6.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

== Building FIFECHAN version 0.1.4 using build type ''.
--     Source directory is '/home/mar/workspace/python/src/fifechan'.
--     Build  directory is '/home/mar/workspace/python/src/fifechan/_build'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found SDL2: /usr/include/SDL2 (found version "2.0.5") 
-- Found SDL2_image: /usr/include/SDL2 (found version "2.0.1")                                                                                                               
-- Fifechan Makefiles have been generated!                                                                                                                                   
-- Configuring done                                                                                                                                                          
-- Generating done                                                                                                                                                           
CMake Warning:                                                                                                                                                               
  Manually-specified variables were not used by the project:                                                                                                                 
                                                                                                                                                                             
    PYTHON_EXECUTABLE                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                          
-- Build files have been written to: /home/mar/workspace/python/src/fifechan/_build                                                                                          
```

**Comment by MarkusHackspacher** [comment]
I hab delete fifechan directory and clone the actual new from github and have the same error. 
I tested it with Clang 4.0.1 and have the same error.

Have somebody any Idea?

**Comment by helios2000** [comment]
Do you use fife master too? The drawOutline method is new so that you need fifechan and fife masters together.

**Comment by MarkusHackspacher** [comment]
Yes, I use the newst fifechan and fifenergie from github master, you can see this my comment:
== Building FIFE version 0.4.1+build.4cf99f2

**Comment by LinuxDonald** [comment]
Hm than I really don't know what could be the problem :-( clang swig are not the problem here.

**Comment by LinuxDonald** [comment]
When I will find the time I will setup an vm with Debian sid and Test it.

**Comment by MarkusHackspacher** [comment]
I tested it on debian 9.1 at a live dvd. It works,



$ python3 -c 'from fife import fife; print(fife.getVersion())'
0.4.1+build.937a230



fifechan$ mkdir _build; cd _build; cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done

== Building FIFECHAN version 0.1.4 using build type ''.
--     Source directory is '/home/user/workspace/fifechan'.
--     Build  directory is '/home/user/workspace/fifechan/_build'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found SDL2: /usr/include/SDL2 (found version "2.0.5") 
-- Found SDL2_image: /usr/include/SDL2 (found version "2.0.1") 
-- Fifechan Makefiles have been generated!
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/workspace/fifechan/_build





$ mkdir _build1; cd _build1; cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.5 PYTHON_INCLUDE_DIR=/usr/include/python3.5m -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
== Updating version.h with version information and git meta data.
-- Set CMAKE_BUILD_TYPE to default 'Release'.

== Building FIFE version 0.4.1+build.937a230 using build type 'Release'.
--     Source directory is '/home/user/workspace/fifengine'.
--     Build  directory is '/home/user/workspace/fifengine/_build1'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/user/workspace/fifengine/../fifengine-dependencies'.

--     CMake version is '3.7.2'.
--     CXX Compiler ID: 'GNU'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so (found version "2.0.1") 
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so (found version "2.0.14") 
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.28") 
-- Found OPENALSOFT: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so  
-- Found vorbisfile: /usr/lib/x86_64-linux-gnu/libvorbisfile.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so (found version "2.0.0") 
-- Found PythonInterp: /usr/bin/python3.5 (found version "3.5.3") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found version "3.5.3") 
-- Found the following FifeChan libraries:
--   fifechan_sdl
-- Found FIFECHAN: /usr/lib/libfifechan.so   
-- Found the following FifeChan libraries:
--   fifechan_opengl
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.10") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found suitable exact version "3.5.3") 
--     Python install directory is '/usr/lib/python3/dist-packages/fife'.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/user/workspace/fifengine/_build1

**Comment by MarkusHackspacher** [comment]
I have installed Debian Sid in virtualbox and try to build fifengine and get this fault:

```
fifengine/_build1$ make
[  0%] Swig source
Scanning dependencies of target _fife
[  1%] Building CXX object CMakeFiles/_fife.dir/fifePYTHON_wrap.cxx.o

c++: internal compiler error: Getötet (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
CMakeFiles/_fife.dir/build.make:143: die Regel für Ziel „CMakeFiles/_fife.dir/fifePYTHON_wrap.cxx.o“ scheiterte
make[2]: *** [CMakeFiles/_fife.dir/fifePYTHON_wrap.cxx.o] Fehler 4
CMakeFiles/Makefile2:99: die Regel für Ziel „CMakeFiles/_fife.dir/all“ scheiterte
make[1]: *** [CMakeFiles/_fife.dir/all] Fehler 2
Makefile:129: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2
```

**Comment by LinuxDonald** [comment]
@MarkusHackspacher maybe any news about it? Is it still an problem?

**Comment by MarkusHackspacher** [comment]
I have it not tested with Debian Sid long time.

**Comment by s172262** [comment]
please do the following two commands and report the results.
```
$ env  | grep PYTHONPATH
```
and
```
$ python3 -c "import sys;print (sys.path)"
```

**Comment by MarkusHackspacher** [comment]
`$ env  | grep PYTHONPATH`
Nothing

`$ python3 -c "import sys;print (sys.path)"

['', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/local/lib/python3.6/dist-packages', '/usr/lib/python3/dist-packages']`

**Comment by LinuxDonald** [comment]
Maybe try to compile with clang: -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..

**Comment by LinuxDonald** [comment]
@MarkusHackspacher any news about this?

**Comment by MarkusHackspacher** [comment]
I try it to build, now it is not found cegui, but it is install. libcegui-mk2-0.8.7, libcegui-mk2-dev (0.8.7-2).

```
fifengine$ mkdir _build1; cd _build1; cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.5 PYTHON_INCLUDE_DIR=/usr/include/python3.5m -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
== Updating version.h with version information and git meta data.
-- Set CMAKE_BUILD_TYPE to default 'Release'.

== Building FIFE version 0.4.1+build.bd53d8e using build type 'Release'.
--     Source directory is '/home/mar/workspace/python/src/fifengine'.
--     Build  directory is '/home/mar/workspace/python/src/fifengine/_build1'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/mar/workspace/python/src/fifengine/../fifengine-dependencies'.

--     CMake version is '3.10.2'.
--     CXX Compiler ID: 'GNU'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so (found version "2.0.3") 
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so (found version "2.0.14") 
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34") 
-- Found OPENALSOFT: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so  
-- Found vorbisfile: /usr/lib/x86_64-linux-gnu/libvorbisfile.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so (found version "2.0.0") 
-- Looking for CEGUI...
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Could not locate CEGUI
CMake Error at cmake/FindCEGUI.cmake:247 (message):
  Required library CEGUI not found! Install the library (including dev
  packages) and try again.  If the library is already installed, set the
  missing variables manually in cmake.
Call Stack (most recent call first):
  cmake/FindCEGUI.cmake:490 (findpkg_finish)
  CMakeLists.txt:769 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/mar/workspace/python/src/fifengine/_build1/CMakeFiles/CMakeOutput.log".
See also "/home/mar/workspace/python/src/fifengine/_build1/CMakeFiles/CMakeError.log".
```

**Comment by LinuxDonald** [comment]
Whats the paths to cegui on your system?

**Comment by MarkusHackspacher** [comment]
/usr/bin/CEGUISampleFramework-0.8
/usr/bin/toluappcegui-0.8
/usr/lib/cegui-0.8/libCEGUICoreWindowRendererSet.so
/usr/lib/cegui-0.8/libCEGUIDevILImageCodec.so
/usr/lib/cegui-0.8/libCEGUIExpatParser.so
/usr/lib/cegui-0.8/libCEGUIFreeImageImageCodec.so
/usr/lib/cegui-0.8/libCEGUILibXMLParser.so
/usr/lib/cegui-0.8/libCEGUIRapidXMLParser.so
/usr/lib/cegui-0.8/libCEGUISILLYImageCodec.so
/usr/lib/cegui-0.8/libCEGUITinyXMLParser.so
/usr/lib/cegui-0.8/libCEGUIXercesParser.so
/usr/lib/libCEGUIBase-0.so.2
/usr/lib/libCEGUIBase-0.so.2.4.2
/usr/lib/libCEGUICommonDialogs-0.so.2
/usr/lib/libCEGUICommonDialogs-0.so.2.4.2
/usr/lib/libCEGUIIrrlichtRenderer-0.so.2
/usr/lib/libCEGUIIrrlichtRenderer-0.so.2.4.2
/usr/lib/libCEGUILuaScriptModule-0.so.2
/usr/lib/libCEGUILuaScriptModule-0.so.2.4.2
/usr/lib/libCEGUINullRenderer-0.so.2
/usr/lib/libCEGUINullRenderer-0.so.2.4.2
/usr/lib/libCEGUIOgreRenderer-0.so.2
/usr/lib/libCEGUIOgreRenderer-0.so.2.4.2
/usr/lib/libCEGUIOpenGLRenderer-0.so.2
/usr/lib/libCEGUIOpenGLRenderer-0.so.2.4.2
/usr/lib/python2.7/dist-packages/cegui-0.8/PyCEGUI.so
/usr/lib/python2.7/dist-packages/cegui-0.8/PyCEGUINullRenderer.so
/usr/lib/python2.7/dist-packages/cegui-0.8/PyCEGUIOgreRenderer.so
/usr/lib/python2.7/dist-packages/cegui-0.8/PyCEGUIOpenGLRenderer.so

**Comment by LinuxDonald** [comment]
Yeah there are not python3 support in this cegui.

**Comment by LinuxDonald** [comment]
Should be fixed with: https://github.com/fifengine/fifengine/commit/fa6ea6d229f28fd9bd2718507601dc50bddfb702

**Comment by MarkusHackspacher** [comment]
Now looks good.

```
$ mkdir _build1; cd _build1; cmake -DPYTHON_EXECUTABLE=/usr/bin/python3.6 PYTHON_INCLUDE_DIR=/usr/include/python3.6m -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
== Updating version.h with version information and git meta data.
-- Set CMAKE_BUILD_TYPE to default 'Release'.

== Building FIFE version 0.4.1+build.fa6ea6d using build type 'Release'.
--     Source directory is '/home/mar/workspace/python/src/fifengine'.
--     Build  directory is '/home/mar/workspace/python/src/fifengine/_build1'.
--     Installation path is '/usr' (set -DCMAKE_INSTALL_PREFIX=<path> to change).
--     Dependencies folder: '/home/mar/workspace/python/src/fifengine/../fifengine-dependencies'.

--     CMake version is '3.11.2'.
--     CXX Compiler ID: 'GNU'.
--     CXX Compiler Flags: '-std=c++11 -fPIC  -O2 -Wno-error'.

-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2: /usr/lib/x86_64-linux-gnu/libSDL2main.a;/usr/lib/x86_64-linux-gnu/libSDL2.so;-lpthread  
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so (found version "2.0.3") 
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so (found version "2.0.14") 
-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   system
--   filesystem
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34") 
-- Found OPENALSOFT: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Found OGG: /usr/lib/x86_64-linux-gnu/libogg.so  
-- Found vorbis: /usr/lib/x86_64-linux-gnu/libvorbis.so  
-- Found vorbisfile: /usr/lib/x86_64-linux-gnu/libvorbisfile.so  
CMake Warning (dev) at /usr/share/cmake-3.11/Modules/FindOpenGL.cmake:270 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:766 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so (found version "2.0.0") 
-- Found PythonInterp: /usr/bin/python3.6 (found version "3.6.6") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found version "3.6.6") 
-- Found the following FifeChan libraries:
--   fifechan_sdl
-- Found FIFECHAN: /usr/lib/libfifechan.so   
-- Found the following FifeChan libraries:
--   fifechan_opengl
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.12") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable exact version "3.6.6") 
--     Python install directory is '/usr/lib/python3/dist-packages/fife'.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mar/workspace/python/src/fifengine/_build1
```
