### ISSUE TITLE
Symbol not found: _gleDestroyGC

### ISSUE THREAD

**Issue by s172262** [fifengine/fifengine#1044]
```
$ unknown-horizons 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/fife/fife.py", line 18, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/fife/_fife.so, 2): Symbol not found: _gleDestroyGC
  Referenced from: /usr/local/opt/gle/lib/libgle.3.dylib
  Expected in: flat namespace
 in /usr/local/opt/gle/lib/libgle.3.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/unknown-horizons", line 385, in <module>
    main()
  File "/usr/local/bin/unknown-horizons", line 114, in main
    import horizons.main
  File "/usr/local/lib/python3.6/site-packages/horizons/main.py", line 41, in <module>
    from fife import fife as fife_module
  File "/usr/local/lib/python3.6/site-packages/fife/fife.py", line 21, in <module>
    _fife = swig_import_helper()
  File "/usr/local/lib/python3.6/site-packages/fife/fife.py", line 20, in swig_import_helper
    return importlib.import_module('_fife')
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/fife/_fife.so, 2): Symbol not found: _gleDestroyGC
  Referenced from: /usr/local/opt/gle/lib/libgle.3.dylib
  Expected in: flat namespace
 in /usr/local/opt/gle/lib/libgle.3.dylib
```
_gleDestroyGC is ...
```
$ otool -L /usr/local/opt/gle/lib/libgle.3.dylib
/usr/local/opt/gle/lib/libgle.3.dylib:
	/usr/local/opt/gle/lib/libgle.3.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)

$ nm -o /usr/local/opt/gle/lib/libgle.3.dylib |grep "gleDestroyGC"
/usr/local/opt/gle/lib/libgle.3.dylib:                  U _gleDestroyGC
```

```
$ nm -o /usr/local/lib/python3.6/site-packages/fife/_fife.so |grep "_gle"
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U ___glewActiveTexture
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U ___glewBindFramebufferEXT
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U ___glewClientActiveTexture
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U ___glewDeleteFramebuffers
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U ___glewFramebufferTexture2DEXT
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U ___glewGenFramebuffers
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U _glewExperimental
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U _glewGetErrorString
/usr/local/lib/python3.6/site-packages/fife/_fife.so:                  U _glewInit
```

```
$ otool -L /usr/local/lib/python3.6/site-packages/fife/_fife.so
/usr/local/lib/python3.6/site-packages/fife/_fife.so:
	/usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib (compatibility version 8.0.0, current version 8.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 22.0.0)
	/usr/local/opt/sdl2_image/lib/libSDL2_image-2.0.0.dylib (compatibility version 3.0.0, current version 3.0.0)
	/usr/local/opt/sdl2_ttf/lib/libSDL2_ttf-2.0.0.dylib (compatibility version 15.0.0, current version 15.0.0)
	/usr/local/opt/openal-soft/lib/libopenal.1.dylib (compatibility version 1.0.0, current version 1.18.2)
	/usr/local/opt/boost/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/boost/lib/libboost_filesystem-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/libpng/lib/libpng16.16.dylib (compatibility version 51.0.0, current version 51.0.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/local/opt/libvorbis/lib/libvorbisfile.3.dylib (compatibility version 7.0.0, current version 7.7.0)
	/usr/local/opt/libvorbis/lib/libvorbis.0.dylib (compatibility version 5.0.0, current version 5.8.0)
	/usr/local/opt/tinyxml/lib/libtinyxml.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/local/opt/glew/lib/libGLEW.2.1.dylib (compatibility version 2.1.0, current version 2.1.0)
	/usr/local/opt/fifechan/lib/libfifechan.0.1.4.dylib (compatibility version 0.1.4, current version 0.1.4)
	/usr/local/opt/fifechan/lib/libfifechan_sdl.0.1.4.dylib (compatibility version 0.1.4, current version 0.1.4)
	/usr/local/opt/fifechan/lib/libfifechan_opengl.0.1.4.dylib (compatibility version 0.1.4, current version 0.1.4)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

**Comment by s172262** [comment]
It does not occur after re-build gle.
