### ISSUE TITLE
MouseScroll Button Pressing can crash fife

### ISSUE THREAD

**Issue by LinuxDonald** [fifengine/fifengine#1062]
Pressing MouseWheel can crash it. But not always happens.

```
linuxdonald@linuxdonald-desktop:~/dev/fifengine-demos/rio_de_hola$ python3 ./run.py
Using the FIFE python module found here:  /usr/lib/python3/dist-packages/fife
Controller:LOG:Fifengine v0.4.1+build.fa371ca
Controller:LOG:================== Engine initialize start =================
Controller:LOG:Time manager created
Controller:LOG:Creating VFS
Controller:LOG:Adding root directory to VFS
Controller:LOG:Adding zip provider to VFS
Controller:LOG:Engine pre-init done
Controller:LOG:Creating event manager
Controller:LOG:Creating resource managers
Controller:LOG:Creating render backend
Controller:LOG:OpenGL Render backend created
Controller:LOG:Initializing render backend
Controller:LOG:Querying device capabilities
Controller:LOG:Creating main screen
Controller:LOG:Main screen created
Controller:LOG:Creating sound manager
Controller:LOG:Creating renderers
Controller:LOG:Creating model
Controller:LOG:Adding pathers to model
Controller:LOG:Adding grid prototypes to model
Controller:LOG:Engine initialized
Traceback (most recent call last):
TypeError: in method 'IMouseListener_mouseWheelMovedRight', argument 1 of type 'FIFE::IMouseListener *'

Traceback (most recent call last):
  File "./run.py", line 182, in <module>
    main()
  File "./run.py", line 166, in main
    app.run()
  File "/usr/lib/python3/dist-packages/fife/extensions/basicapplication.py", line 212, in run
    retval = self.mainLoop()
  File "/usr/lib/python3/dist-packages/fife/extensions/basicapplication.py", line 230, in mainLoop
    self.engine.pump()
RuntimeError: Caught a director exception
AL lib: (EE) alc_cleanup: 1 device not closed

```

**Comment by jmdejong** [comment]
The cause for this is that the mouseListeners do not implement all of fife::IMouseListener's methods.
mouseWheelMovedRight and mouseWheelMovedLeft were added last years, and aren't implemented in most applications using fife.

I think the more general problem is that not implementing a IMouseListener method crashes with an unhelpful error when the method is called.
