### ISSUE TITLE
applyOnlySuitable fails on functools.partial

### ISSUE THREAD

**Issue by totycro** [fifengine/fifengine#638]
If a callback generated by functools.partial is passed to applyOnlySuitable, it will crash, since none of the ifs in applyOnlySuitable will catch this kind of function:

``` pytb
Traceback (most recent call last):
  File "/home/totycro/code/unknown-horizons/fife/engine/python/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
  File "/home/totycro/code/unknown-horizons/fife/engine/python/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(*args,**kwargs)
  File "/home/totycro/code/unknown-horizons/fife/engine/python/fife/extensions/pychan/events.py", line 164, in delayed_f
    f( event )
  File "/home/totycro/code/unknown-horizons/fife/engine/python/fife/extensions/pychan/events.py", line 327, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
  File "/home/totycro/code/unknown-horizons/fife/engine/python/fife/extensions/pychan/tools.py", line 55, in applyOnlySuitable
    if code.co_flags & 8:
UnboundLocalError: local variable 'code' referenced before assignment
```

**Comment by jakoch** [comment]
- [applyOnlySuitable()](https://github.com/fifengine/fifengine/blob/main/src/python/fife/extensions/pychan/tools.py#L10) 
- When a partial is passed:
  - first two hasattr checks fail
  - the third check (__call__) succeeds
    - reassigning func = func.__call__ won't help
  - the inner checks on the __call__ method also fails
  - code is never assigned, which leads to UnboundLocalError

- so basically, we need to unwrap the partial object to access func
