### ISSUE TITLE
Throw a dedicated exception in case a image can't be found

### ISSUE THREAD

**Issue by Teemperor** [fifengine/fifengine#875]
Loading an non-existing image via fife just raises a generic RuntimeError that prevents effectively handling the situation (without parsing the exception). Raising a dedicated error type for this would be a good solution.

Example traceback of the use-case:

Traceback (most recent call last):
```
 File "/usr/lib/python2.7/site-packages/fife/extensions/fife_timer.py", line 125, in updateEvent
    self._callback()
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 83, in real_callback
    callback(_args,__kwargs)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 173, in delayed_f
    f( event )
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/events.py", line 351, in captured_f
    tools.applyOnlySuitable(self_ref().callbacks[group_name][event_name],event=event,widget=self_ref().widget_ref())
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/tools.py", line 60, in applyOnlySuitable
    return func(_args,**kwargs)
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/util/python/callback.py", line 47, in __call__
    return self.callback(_self.args, *_self.kwargs)
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/gui/tabs/barrackstabs.py", line 110, in start_production
    self.instance.session.ingame_gui.get_cur_menu().show_tab(0)
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 120, in show_tab
    self.show()
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 145, in show
    self._draw_widget()
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/gui/tabs/tabwidget.py", line 138, in _draw_widget
    self.current_tab.refresh()
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/gui/tabs/boatbuildertabs.py", line 71, in refresh
    progress_container, cancel_container, production_lines)
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/gui/tabs/boatbuildertabs.py", line 86, in show_production_is_active_container
    self.update_production_is_active_container(progress_container, container_active, cancel_container, production_lines)
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/gui/tabs/boatbuildertabs.py", line 91, in update_production_is_active_container
    self.update_queue(container_active)
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/gui/tabs/boatbuildertabs.py", line 160, in update_queue
    icon = Icon(name=icon_name, image=image, helptext=helptext)
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/engine/pychan_util.py", line 130, in wrapper
    func(self, _args, *_kwargs)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/widgets/icon.py", line 91, in __init__
    self.image = image
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/widgets/icon.py", line 126, in _setImage
    self._image = source
 File "/home/teemperor/workspace/uh/unknown-horizons/horizons/engine/pychan_util.py", line 64, in wrapper
    return func(self, obj, image)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/properties.py", line 92, in __set__
    image_info["image"] = get_manager().loadImage(image)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/internal.py", line 249, in loadImage
    return self.hook.load_image(filename)
 File "/usr/lib/python2.7/site-packages/fife/extensions/pychan/compat.py", line 88, in _fife_load_image
    img = engine.getImageManager().load(filename)
 File "/usr/lib/python2.7/site-packages/fife/fife.py", line 5398, in load
    return _fife.ImageManager_load(self, *args)
RuntimeError: _[NotFound]_ , Something was searched, but not found :: content/gui/icons/thumbnails/1000023.png
```

Related issue in UH: https://github.com/unknown-horizons/unknown-horizons/pull/2352

**Comment by LinuxDonald** [comment]
https://github.com/fifengine/fifengine/issues/548

Maybe the same error?

**Comment by jakoch** [comment]
I spend some time on tracking the issue down.
The last two lines of the log point us here:
- [`extensions/pychan/compat.py` - `_fife_load_image`](https://github.com/fifengine/fifengine/blob/d5d0544d952fa26dc77955221221a2daf9eb03ba/engine/python/fife/extensions/pychan/compat.py#L87)
- [`imagemanager.cpp` - `ImageManager::load(const std::string& name, IResourceLoader* loader)`](https://github.com/fifengine/fifengine/blob/ad585a21430136be96b332da712f5d3f31083f0a/engine/core/video/imagemanager.cpp#L110)

----

- I don't see where the `RuntimeError _[NotFound]_` comes from, because there is only a `FL_WARN(_log, ...` call, see
https://github.com/fifengine/fifengine/blob/ad585a21430136be96b332da712f5d3f31083f0a/engine/core/video/imagemanager.cpp#L126
- We could do this on the Python level: check `img` and `throw`, here https://github.com/fifengine/fifengine/blob/master/engine/python/fife/extensions/pychan/compat.py#L88
- I think it would be better to throw on the cpp level and apply the same exception logic we already have in the atlas loader: https://github.com/fifengine/fifengine/blob/ad585a21430136be96b332da712f5d3f31083f0a/engine/core/loaders/native/map/atlasloader.cpp#L162

**Comment by Niektory** [comment]
To me it looks that a proper NotFound exception (defined here: https://github.com/fifengine/fifengine/blob/master/engine/core/util/base/exception.h#L77) is thrown on the C++ level, it just gets lost in the translation to Python.

I believe what's needed is additional code in the SWIG interface file: https://github.com/fifengine/fifengine/blob/master/engine/swigwrappers/python/fife.i.templ.cm#L131-L160
