### ISSUE TITLE
fife soundemitter lets UH hang

### ISSUE THREAD

**Issue by MasterofJOKers** [fifengine/fifengine#973]
I clicked a lot and fast on a tab in Unknown-Horizons, which is supposed to make a sound every time. After some clicks, there's no sound any more and if I keep clicking longer, UH hangs. Attaching gdb to the process shows the following backtrace:
```
(gdb) backtrace
#0  0x00007fdec38d48ad in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#1  0x00007fdec389d3a5 in alSourceUnqueueBuffers () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#2  0x00007fdec51d6bb3 in FIFE::SoundEmitter::updateEvent(unsigned int) ()
   from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#3  0x00007fdec529155b in FIFE::TimeEvent::managerUpdateEvent(unsigned int) ()
   from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#4  0x00007fdec52917e1 in FIFE::TimeManager::update() () from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#5  0x00007fdec51d97e0 in FIFE::Engine::pump() () from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#6  0x00007fdec4e34e1d in ?? () from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#7  0x000056175fe6f3fa in PyEval_EvalFrameEx ()
#8  0x000056175fe74c7f in PyEval_EvalFrameEx ()
```
and occasionally
```
#0  0x00007fdec38d3eb2 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#1  0x00007fdec38d4865 in ?? () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#2  0x00007fdec389fe03 in alSourceStopv () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#3  0x00007fdec389fed7 in alSourceStop () from /usr/lib/x86_64-linux-gnu/libopenal.so.1
#4  0x00007fdec51d6c91 in FIFE::SoundEmitter::updateEvent(unsigned int) ()
   from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#5  0x00007fdec529155b in FIFE::TimeEvent::managerUpdateEvent(unsigned int) ()
   from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#6  0x00007fdec52917e1 in FIFE::TimeManager::update() () from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#7  0x00007fdec51d97e0 in FIFE::Engine::pump() () from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#8  0x00007fdec4e34e1d in ?? () from /usr/lib/python2.7/dist-packages/fife/_fife.x86_64-linux-gnu.so
#9  0x000056175fe6f3fa in PyEval_EvalFrameEx ()
```

**Comment by helios2000** [comment]
Problem should be fixed with https://github.com/fifengine/fifengine/pull/1016

**Comment by LinuxDonald** [comment]
Fixed. Tested it. THX @helios2000
